name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Mostrar permisos antes de cambio
        run: ls -la

      - name: Dar permisos de ejecución a Gradlew
        run: chmod +x gradlew

      - name: Convertir Gradlew a formato UNIX (evita errores en Linux)
        run: sudo apt-get install dos2unix && dos2unix gradlew

      - name: Mostrar permisos después de cambio
        run: ls -la

      - name: Build JAR con Gradle
        run: ./gradlew build

      - name: Iniciar sesión en Docker Hub
        run: echo "LayLa102232" | docker login -u "juancamco" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t juancamco/microservicio:latest .

      - name: Subir imagen a Docker Hub
        run: docker push juancamco/microservicio:latest
